version: '3'

services:
  db:
    image: mariadb   # Nombre de la imagen existente de MariaDB
    container_name: "mysql-mariadb"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: agustin123
      MYSQL_DATABASE: productos_db
    volumes:
      - './mysql:/var/lib/mysql'
    networks:
      mynet:
        ipv4_address: 192.168.5.2

  dockerserver:
    build:
      context: ./dockerserver
      dockerfile: Dockerfile
    container_name: server_express
    restart: always
    ports:
      - "4000:3000"
    depends_on:
      - db
    networks:
      mynet:
        ipv4_address: 192.168.5.3

  front-end:
    container_name: front-end-React
    build:
      context: ./front-end
      dockerfile: Dockerfile
    depends_on:
      - dockerserver
    ports:
      - 3001:3001
    networks:
      mynet:
        ipv4_address: 192.168.5.4

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
          ip_range: 192.168.5.0/24
          gateway: 192.168.0.1